import {Evaluation,Problem,Submission} from './types';
const has=(s:string,...terms:string[])=>terms.some(t=>s.toLowerCase().includes(t.toLowerCase()));
export function evaluate(problem:Problem,s:Submission):Evaluation{
 const all=Object.values(s).join('\n'); const items:any[]=[]; const add=(category:any,severity:any,title:string,detail:string,action:string)=>items.push({category,severity,title,detail,action});
 const filled=Object.values(s).filter(v=>v.trim().length>20).length;
 if(filled<4)add('Completeness','critical','Several design sections are too thin','A meaningful LLD attempt needs responsibilities, relationships, behaviour and trade-offs, not only class names.','Expand each section with concrete decisions and one example flow.'); else add('Completeness','pass','Core design is present','The submission contains enough structured information to evaluate the design.','Keep the same structure for future attempts.');
 if(has(all,'interface')||has(all,'abstract')||has(all,'strategy')||has(all,'policy'))add('Abstraction','pass','A variation point is identified','You have introduced an abstraction for behavior that may change.','Explain why that interface owns the variation.'); else add('Abstraction','warn','Variation points are not explicit','The prompt contains behavior that may change, but the submission does not clearly isolate it.','Add an interface such as a Strategy/Policy where behavior varies.');
 if(has(all,'god object')||has(all,'single responsibility')||has(all,'responsibility')||has(all,'cohesion'))add('Responsibilities','pass','Responsibilities are discussed','The design acknowledges responsibility boundaries.','Name the owner of each important behavior explicitly.'); else add('Responsibilities','warn','Responsibility boundaries are unclear','Class lists alone do not show who owns behavior.','For each major class, state one responsibility and one collaborator.');
 if(has(all,'composition')||has(all,'has-a')||has(all,'aggregation'))add('Relationships','pass','Relationships consider composition','The submission considers ownership/composition rather than only inheritance.','Clarify lifecycle: who creates, owns and releases each object.'); else add('Relationships','warn','Relationships need more detail','The evaluator cannot tell which objects own or merely reference others.','Use phrases like "Floor owns Spot" or "Controller references Elevator".');
 if(has(all,'edge')||has(all,'invalid')||has(all,'failure')||has(all,'exception'))add('Behaviour','pass','Failure paths are considered','The design includes non-happy-path behaviour.','Add one concrete sequence for the hardest failure path.'); else add('Behaviour','warn','Edge cases are missing','Interview-quality LLD should explain invalid requests and state transitions.','Add at least two failure/edge cases and the responsible class.');
 if(has(s.tradeoffs,'trade')||has(s.tradeoffs,'why')||has(s.tradeoffs,'alternative'))add('Trade-offs','pass','Trade-offs are stated','You explain decisions instead of presenting one design as universally correct.','Keep alternatives concise and tie each trade-off to a requirement.'); else add('Trade-offs','warn','Trade-offs are underdeveloped','LLD is evaluated on judgement as well as structure.','Name one alternative you rejected and why.');
 const critical=items.filter(x=>x.severity==='critical').length,warns=items.filter(x=>x.severity==='warn').length; const score=Math.max(0,Math.min(100,Math.round(100-critical*18-warns*8+(filled>=5?8:0))));
 const strengths=items.filter(x=>x.severity==='pass').map(x=>x.title).slice(0,3); const next=items.filter(x=>x.severity!=='pass').map(x=>x.action).slice(0,3);
 return {score,items,summary:score>=80?'Strong foundation. The design is structured enough to discuss in an interview.':score>=60?'Promising attempt. Tighten responsibilities, relationships and edge cases before repeating the problem.':'The attempt needs more concrete object behaviour before it can be evaluated confidently.',strengths,nextSteps:next};
}
