import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowLeft,ArrowRight,CheckCircle2,Clock3,History,Lightbulb,Play,RotateCcw,Send,Sparkles,Target,TriangleAlert}from'lucide-react';import{problems}from'./data';import{evaluate}from'./evaluator';import{loadAttempts,saveAttempt}from'./storage';import{Attempt,Problem,Submission}from'./types';import'./styles.css';
const blank:Submission={requirements:'',classes:'',relationships:'',behaviour:'',tradeoffs:'',code:''};
function App(){const[screen,setScreen]=useState<'home'|'practice'|'feedback'|'history'>('home');const[problem,setProblem]=useState<Problem>(problems[0]);const[sub,setSub]=useState<Submission>(blank);const[attempts,setAttempts]=useState<Attempt[]>(loadAttempts());const[hint,setHint]=useState(0);const[evaln,setEvaln]=useState<any>();const[elapsed,setElapsed]=useState(0);
 useEffect(()=>{if(screen!=='practice')return;const t=setInterval(()=>setElapsed(e=>e+1),1000);return()=>clearInterval(t)},[screen]);
 const mins=Math.floor(elapsed/60).toString().padStart(2,'0'),secs=(elapsed%60).toString().padStart(2,'0');
 const start=(p:Problem)=>{setProblem(p);setSub(blank);setHint(0);setEvaln(undefined);setElapsed(0);setScreen('practice')};
 const submit=()=>{const e=evaluate(problem,sub);const now=new Date().toISOString();const a:Attempt={id:crypto.randomUUID(),problemId:problem.id,createdAt:now,updatedAt:now,status:'evaluated',submission:sub,evaluation:e};saveAttempt(a);setAttempts(loadAttempts());setEvaln(e);setScreen('feedback')};
 const stat=useMemo(()=>({solved:attempts.length,avg:attempts.length?Math.round(attempts.reduce((x,a)=>x+(a.evaluation?.score||0),0)/attempts.length):0}),[attempts]);
 return <div className="app"><header><div className="brand"><div className="logo">⌘</div><div><b>LLD Forge</b><span>Practice → design → feedback → repeat</span></div></div><nav><button onClick={()=>setScreen('home')} className={screen==='home'?'active':''}>Problems</button><button onClick={()=>setScreen('history')} className={screen==='history'?'active':''}><History size={16}/>History</button></nav></header>
 {screen==='home'&&<main className="container"><section className="hero"><div><p className="eyebrow">LOW-LEVEL DESIGN PRACTICE</p><h1>Design systems.<br/><em>Understand why they work.</em></h1><p className="lede">Practice interview-style LLD problems and get explainable feedback on responsibilities, abstractions, relationships and trade-offs.</p><button className="primary" onClick={()=>start(problems[0])}><Play size={17}/> Start a practice</button></div><div className="loop"><div className="loop-title">THE PRACTICE LOOP</div>{['Choose a problem','Design your solution','Submit for review','Learn from feedback','Try again'].map((x,i)=><div className="loop-row" key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></section>
 <section className="stats"><div><Target/><b>{stat.solved}</b><span>attempts</span></div><div><Sparkles/><b>{stat.avg||'—'}</b><span>avg. score</span></div><div><CheckCircle2/><b>6</b><span>evaluation signals</span></div></section>
 <div className="section-head"><div><p className="eyebrow">PROBLEM LIBRARY</p><h2>Pick a system to design</h2></div><span>{problems.length} focused problems</span></div><div className="cards">{problems.map(p=><article className="card" key={p.id}><div className="card-top"><span className={'difficulty '+p.difficulty.toLowerCase()}>{p.difficulty}</span><span><Clock3 size={14}/>{p.time} min</span></div><h3>{p.title}</h3><p>{p.prompt}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><button className="text-btn" onClick={()=>start(p)}>Practice <ArrowRight size={15}/></button></article>)}</div></main>}
 {screen==='practice'&&<main className="practice"><div className="practice-head"><button className="back" onClick={()=>setScreen('home')}><ArrowLeft size={16}/> Problems</button><div><span className={'difficulty '+problem.difficulty.toLowerCase()}>{problem.difficulty}</span><h1>{problem.title}</h1></div><div className="timer"><Clock3 size={17}/>{mins}:{secs}</div></div><div className="workspace"><aside><p className="eyebrow">PROBLEM</p><p className="prompt">{problem.prompt}</p><h4>Requirements</h4><ul>{problem.requirements.map(r=><li key={r}>{r}</li>)}</ul><div className="hintbox"><div><Lightbulb size={16}/><b>Hint {hint}/{problem.hints.length}</b></div>{hint>0&&<p>{problem.hints[hint-1]}</p>}<button onClick={()=>setHint(h=>Math.min(problem.hints.length,h+1))} disabled={hint>=problem.hints.length}>Reveal next hint</button></div></aside><section className="editor"><div className="editor-title"><div><b>Your design</b><span>Explain the decisions, not just class names.</span></div><button className="submit" onClick={submit}><Send size={15}/> Submit for feedback</button></div><Field label="1 · Requirements & assumptions" value={sub.requirements} set={(v:string)=>setSub({...sub,requirements:v})} placeholder="What is in scope? What assumptions are you making?"/><Field label="2 · Classes & responsibilities" value={sub.classes} set={(v:string)=>setSub({...sub,classes:v})} placeholder="Example: ParkingLot coordinates entry/exit; Floor owns spots..."/><Field label="3 · Relationships & abstractions" value={sub.relationships} set={(v:string)=>setSub({...sub,relationships:v})} placeholder="Composition, inheritance, interfaces, dependency direction..."/><Field label="4 · Behaviour & edge cases" value={sub.behaviour} set={(v:string)=>setSub({...sub,behaviour:v})} placeholder="Walk through one happy path and at least two failure paths."/><Field label="5 · Trade-offs" value={sub.tradeoffs} set={(v:string)=>setSub({...sub,tradeoffs:v})} placeholder="What alternative did you reject and why?"/><Field label="6 · Optional code sketch" value={sub.code} set={(v:string)=>setSub({...sub,code:v})} placeholder="Pseudo-code or key interfaces. Keep it focused." mono/></section></div></main>}
 {screen==='feedback'&&<main className="container feedback"><button className="back" onClick={()=>setScreen('practice')}><ArrowLeft size={16}/> Back to attempt</button><section className="scorehero"><div><p className="eyebrow">EVALUATION COMPLETE</p><h1>Feedback you can act on.</h1><p>{evaln.summary}</p></div><div className="score"><b>{evaln.score}</b><span>/ 100</span></div></section><div className="feedback-grid"><section><h2>Signals</h2>{evaln.items.map((x:any)=><div className="feedback-item" key={x.title}><div className={'signal '+x.severity}>{x.severity==='pass'?<CheckCircle2/>:<TriangleAlert/>}</div><div><div className="fi-head"><b>{x.title}</b><span>{x.category}</span></div><p>{x.detail}</p><small>Next: {x.action}</small></div></div>)}</section><aside><div className="side-card"><p className="eyebrow">WHAT WORKED</p>{evaln.strengths.map((x:string)=><div className="mini" key={x}><CheckCircle2 size={16}/>{x}</div>)}</div><div className="side-card"><p className="eyebrow">NEXT ITERATION</p>{evaln.nextSteps.map((x:string)=><div className="mini" key={x}><ArrowRight size={16}/>{x}</div>)}</div><button className="primary full" onClick={()=>start(problem)}><RotateCcw size={16}/> Try {problem.title} again</button></aside></div></main>}
 {screen==='history'&&<main className="container"><section className="section-head"><div><p className="eyebrow">YOUR PRACTICE HISTORY</p><h1>Progress, not perfection.</h1></div></section>{attempts.length===0?<div className="empty">No attempts yet. Pick a problem and submit your first design.</div>:<div className="history-list">{attempts.map(a=>{const p=problems.find(x=>x.id===a.problemId)!;return <article key={a.id}><div><span className={'difficulty '+p.difficulty.toLowerCase()}>{p.difficulty}</span><h3>{p.title}</h3><small>{new Date(a.createdAt).toLocaleString()}</small></div><div className="history-score">{a.evaluation?.score}<span>/100</span></div><button className="text-btn" onClick={()=>{setProblem(p);setSub(a.submission);setEvaln(a.evaluation);setScreen('feedback')}}>Review <ArrowRight size={15}/></button></article>})}</div>}</main>}
 </div>}
function Field({label,value,set,placeholder,mono}:{label:string;value:string;set:(v:string)=>void;placeholder:string;mono?:boolean}){return <label className="field"><span>{label}</span><textarea className={mono?'mono':''} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>}
createRoot(document.getElementById('root')!).render(<App/>);
